<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="ClosedXML" Version="0.104.2" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="8.0.2" />
    <PackageReference Include="Microsoft.Extensions.Options" Version="8.0.2" />
    <PackageReference Include="Microsoft.Playwright" Version="1.52.0" />
    <PackageReference Include="Microsoft.SemanticKernel" Version="1.38.0" />
    <PackageReference Include="PdfPig" Version="0.1.10" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Apropriacao.Domain\Apropriacao.Domain.csproj" />
  </ItemGroup>

</Project>